// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.6
// source: api/hack/v1/hack.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Hack_Hello_FullMethodName = "/hack.v1.Hack/Hello"
)

// HackClient is the client API for Hack service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HackClient interface {
	Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type hackClient struct {
	cc grpc.ClientConnInterface
}

func NewHackClient(cc grpc.ClientConnInterface) HackClient {
	return &hackClient{cc}
}

func (c *hackClient) Hello(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Hack_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HackServer is the server API for Hack service.
// All implementations must embed UnimplementedHackServer
// for forward compatibility.
type HackServer interface {
	Hello(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedHackServer()
}

// UnimplementedHackServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHackServer struct{}

func (UnimplementedHackServer) Hello(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedHackServer) mustEmbedUnimplementedHackServer() {}
func (UnimplementedHackServer) testEmbeddedByValue()              {}

// UnsafeHackServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HackServer will
// result in compilation errors.
type UnsafeHackServer interface {
	mustEmbedUnimplementedHackServer()
}

func RegisterHackServer(s grpc.ServiceRegistrar, srv HackServer) {
	// If the following call pancis, it indicates UnimplementedHackServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Hack_ServiceDesc, srv)
}

func _Hack_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HackServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Hack_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HackServer).Hello(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Hack_ServiceDesc is the grpc.ServiceDesc for Hack service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hack_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hack.v1.Hack",
	HandlerType: (*HackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Hack_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/hack/v1/hack.proto",
}
