// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v4.25.6
// source: api/hack/v1/hack.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHackHello = "/hack.v1.Hack/Hello"

type HackHTTPServer interface {
	Hello(context.Context, *Request) (*Response, error)
}

func RegisterHackHTTPServer(s *http.Server, srv HackHTTPServer) {
	r := s.Route("/")
	r.GET("/hello", _Hack_Hello0_HTTP_Handler(srv))
}

func _Hack_Hello0_HTTP_Handler(srv HackHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in Request
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHackHello)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Hello(ctx, req.(*Request))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*Response)
		return ctx.Result(200, reply)
	}
}

type HackHTTPClient interface {
	Hello(ctx context.Context, req *Request, opts ...http.CallOption) (rsp *Response, err error)
}

type HackHTTPClientImpl struct {
	cc *http.Client
}

func NewHackHTTPClient(client *http.Client) HackHTTPClient {
	return &HackHTTPClientImpl{client}
}

func (c *HackHTTPClientImpl) Hello(ctx context.Context, in *Request, opts ...http.CallOption) (*Response, error) {
	var out Response
	pattern := "/hello"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHackHello))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
